### ISSUE TITLE
Textfield Setting returning FALSE always.

### ISSUE THREAD

**Issue by engdlee** [scofennell/csst-tmd#1]
Hello,
i am learning about the customizer and i stumbled upon your demo theme in css-tricks, i am having an issue adding a simple textfield setting like this:

```
$out['body']['sections']['layout']['settings']['testtext'] = array(

            'type'                 => 'text',
            'label'                => esc_html__( 'test label', 'csst_tmd' ),
            'description'          => esc_html( 'Description test.', 'csst_tmd' ),
            'priority'             => 20,


        );
```
and using var_dump(get_theme_mod( 'testtext'));  in the index.php file,  i always get a `FALSE `value, i can see the control in the section, if i change the value the site preview refreshes but its always returning `FALSE`

If i add the control manually (i mean without using the class the theme provides) the control shows and it works like it should, changing the value in the input will refresh the site preview and show the value i just typed, not sure what is going on, i have been checking the code line by line and i cant seem something wrong in it. Maybe is the hook?

-Lee

**Comment by scofennell** [comment]
Hi!

My suggestion would be to var_dump() all your theme mods ( `get_theme_mods()` )and see how the values are named.  It's likely that in order to get a single theme_mod(), you'd have to do something like,

`get_theme_mod( 'body-layout-testtext' );`

See my example:

https://github.com/scofennell/csst-tmd/blob/master/inc/class.theme-mods.php#L217

**Comment by engdlee** [comment]
That did it!
Thank you!! it was stressing me out.
